### ISSUE TITLE
mdmerge in python 2?

### ISSUE THREAD

**Issue by jsmm** [JeNeSuisPasDave/MarkdownTools#5]
I think this is extremely useful for an md workflow, that would be really useful as a macOS service or workflow.

However, I cannot get it to work in macOS Sierra with original system python 2. I'm not using sudo, and pip seems to install only the multimarkdown not the mdmerge directory.

**Comment by JeNeSuisPasDave** [comment]
You have three options.

The first assumes you installed using `pip install MarkdownTools2 --user python`. You can invoke mdmerge directly, e.g.:

```bash
~/Library/Python/2.7/bin/mdmerge --version
```

or put `~/Library/Python/2.7/bin` on your PATH.

The second is to use `sudo`, e.g. 

```bash
sudo pip install MarkdownTools2
```

If you already have MarkdownTools installed, you should first uninstall it before installing with sudo ... this is a permissions thing.

I don't see any way to get the mdmerge command into `/usr/local/bin` without sudo. (I'd like to know how to get mdmerge into the PATH without requiring sudo.)

The third choice is to use a virtual environment, e.g.:

```bash
mkdir mdt
cd mdt
virtualenv venvsys
. venvsys/bin/activate
pip install -U setuptools
pip install -U pip
pip install MarkdownTools2
```

Going the virtual environment route means activating the virtual environment whenever you want to use mdmerge.  (Note: use `virtualenv --help` to see the options when creating a new virtual environment ... you may want to use the option `--system-site-packages` to expose the system packages.)

NOTE: I use virtual environments all the time. I install different versions of Python using MacPorts and setup virtual environments so that I can use Python3 or so that I can keep a particular version of Python and associated packages stable for a particular project. Worth looking into if you are not already using Python virtual environments.
